version: 2
updates:
  # フロントエンド（npm）
  - package-ecosystem: "npm"
    directory: "/apps/front"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "依存関係"
      - "フロントエンド"
      - "リリースノート除外"
    open-pull-requests-limit: 10

  # バックエンド（Gradle）
  - package-ecosystem: "gradle"
    directory: "/apps/back"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "依存関係"
      - "バックエンド"
      - "リリースノート除外"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "依存関係"
      - "CI/CD"
      - "リリースノート除外"
    open-pull-requests-limit: 10
