name: Build for Docsify and deploy Pages

# ワークフロー共有設定
on:
  workflow_call:
    inputs:
      timeout-minutes:
        description: 'タイムアウト（分）'
        type: number
        default: 10

      document-dir:
        description: 'ドキュメントディレクトリ'
        type: string
        default: 'docs'

      is-deploy:
        description: 'デプロイ実行フラグ'
        type: boolean
        default: false

env:
  TZ: Asia/Tokyo
  DOCUMENT_DIR: ${{ inputs.document-dir }}

permissions:
  contents: read
  pages: write
  id-token: write

# jobs: 動作内容
jobs:
  # ドキュメントのアップロード処理
  upload-docs:
    name: Upload Docs Artifact
    # Github-hosted runner を使用
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    # steps: 動作手順
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCUMENT_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: upload-docs
    if: ${{ inputs.is-deploy }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4