name: Check on pull request

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'apps/front/**'
      - 'apps/back/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# jobs: 動作内容
jobs:
  # 前処理（差分チェック）
  precheck:
    name: Precheck
    uses: ./.github/workflows/review-precheck.yml
    with:
      frontend-dir: apps/front
      component-dir: apps/front/src/components
      backend-dir: apps/back
      # openapi-dir: apps/openapi
      # doc-dir: docs

  # フロントエンドの変更がある場合のみビルド
  frontend-build:
    name: Frontend Build
    needs: precheck
    if: >
      needs.precheck.outputs.frontend-changed != '' ||
      needs.precheck.outputs.component-changed != ''
    uses: ./.github/workflows/build-frontend.yml

  # バックエンドの変更がある場合のみビルド
  backend-build:
    name: Backend Build
    needs: precheck
    if: needs.precheck.outputs.backend-changed != ''
    uses: ./.github/workflows/build-backend.yml

  # OpenAPI チェック（任意）
  # openapi-check:
  #   name: OpenAPI Check
  #   needs: precheck
  #   if: needs.precheck.outputs.openapi-changed != ''
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Run OpenAPI validation here"

  # ドキュメントの変更がある場合、ビルドして公開
  document-build:
    name: Document Build and Deploy
    needs: precheck
    if: needs.precheck.outputs.document-changed != ''
    uses: ./.github/workflows/build-document.yml
    permissions:
      contents: read
      pages: write
      id-token: write